import { IArticle } from '../interface/article.interface';

import {content} from "./content"
export const articles: IArticle [] = [
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'This is a very very long title lets make it more longer title1 This is a very very long title lets make it more longer title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
]