import { IArticle } from '../interface/article.interface';

import {content} from "./content"
export const articles: IArticle [] = [
    {
        authorId: 'authorId1',
        id:'1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'This is a very very long title lets make it more longer title1 This is a very very long title lets make it more longer title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        id:'15',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        id:'14',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        id:'1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        id:'12',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        id:'11',
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        id:'10',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        id:'8',
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        id:'7',
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        id:'6',
        image: 'img', 
        content: content,
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        id:'5',
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        title: 'title1',
        id:'4',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        id:'3',
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
    {
        authorId: 'authorId1',
        authorName: 'author1',
        folderId : 'folderId1', 
        image: 'img', 
        content: content,
        id:'2',
        title: 'title1',
        searchtTags: ['st1','st3','st4'], 
        likes: 6, 
        views: 8, 
        lastupdated: '', 
        createdAt: '',
    },
]